---
name: CI/CD

on: push

jobs:
  test:
    name: Test
    runs-on: golang-1.14
    steps:
      - name: Testing
        run: echo "ОК"
  build:
    name: Build
    needs: test
    runs-on: ubuntu-19.03.12
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/username/package:latest
            ghcr.io/username/package:${{ github.sha }}
