---
name: CI/CD

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14.0"
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      - name: Test End
        run: echo "ОК"
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/app:latest
            ghcr.io/${{ github.repository_owner }}/app:${{ github.sha }}
  deploy_stage:
    name: Deploy to stage
    needs: build
    runs-on: ubuntu-latest
    env: 
      K8S_STAGE_CI_TOKEN: "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqVlNjRE54YkVWWWF6UlpNVmh5UTBWdlducFNORlZmV0cxcU56RjZkRmwzY21sTU5rSkVkMlJ3TldzaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUp6ZEdGblpTSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWamNtVjBMbTVoYldVaU9pSmtaWEJzYjNrdGRHOXJaVzR0TW0xa2FtUWlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObGNuWnBZMlV0WVdOamIzVnVkQzV1WVcxbElqb2laR1Z3Ykc5NUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaU1qSmpPV013WW1RdFkyTTVaQzAwWVdObUxXRTBNbU10TUdVeVpURTFOVGN6TUdSbElpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbk4wWVdkbE9tUmxjR3h2ZVNKOS5zRjV2ZjBaV3VYc2tyVWZJQV9VQmJGRnNsaU5CZUVsbGt4M1RBbVRKZE1tNUIycjVQS0VvQ1FnOFFJMW1oNlMyQ3RoM1Nnb3pMb2FxbjJwV0hySWVQS2dTcUZZdV9wZ2d1WkllRkxEUkVLOEpBQWpwb3dQWjRrRG9iTml2dWNVbnY4M3ZSdlVVakNhbUNCQUZWSnBJZEhsR0hTakltQkpxRXZ6OTFreUttZmNZM080Wm9SbndCYTdyYV9RV010REk5aS1ib1R0RHk1QXJtVkJaUGhaTWxVc3NzUGhPWWd2NFZSQTdyS2xIMURiOEJVWGlNNTVJbGl5OWZlTVNsM2ZKS1BzQjJtZWppSFl5NUJKbWFvSk9pbEZwMDZfb3JoQ0VxMEFxV3VEdzRJVVdtUXFwSVJRaUhucVRGYllNSnZSZk9HWExiNm9Qb0VDb2RQQjdlUUZhQmc="
    steps:
      - run: echo ${{ github.repository_owner }}
      - run: echo ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'
